# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.AddField(
            model_name='choice',
            name='correct_choice',
            field=models.BooleanField(default=0),
        ),
    ]
